CREATE TABLE USER
(
USER_EMAIL VARCHAR(40) PRIMARY KEY,
USER_PASSWORD VARCHAR(40),
USER_NAME VARCHAR(40),
AGE INT
);

CREATE TABLE PLATFORM
(
PLATFORM_NAME VARCHAR(40),
PLAN_TYPE VARCHAR(40),
SCREENS INT,
PLAN_PRICE INT,
PRIMARY KEY (PLATFORM_NAME, PLAN_TYPE)
);

CREATE TABLE ROOM
(
ROOM_NAME VARCHAR(40) PRIMARY KEY,
ADMIN_EMAIL VARCHAR(40),
CAPACITY INT,
MEMBER_CNT INT,
PLATFORM_NAME VARCHAR(40),
PLAN_TYPE VARCHAR(40),
STREAM_ACCOUNT VARCHAR(40),
STREAM_PASSWORD VARCHAR(40),
CONSTRAINT FK_ADMIN FOREIGN KEY(ADMIN_EMAIL) REFERENCES USER(USER_EMAIL),
CONSTRAINT FK_PLAN FOREIGN KEY(PLATFORM_NAME, PLAN_TYPE) REFERENCES PLATFORM(PLATFORM_NAME, PLAN_TYPE)
);

CREATE TABLE REQUESTS
(
USER_EMAIL VARCHAR(40),
ROOM_NAME VARCHAR(40),
MESSAGE VARCHAR(400),
USER_TYPE INT,
CONSTRAINT FK_REQUSER FOREIGN KEY(USER_EMAIL) REFERENCES USER(USER_EMAIL),
CONSTRAINT FK_REQROOM FOREIGN KEY(ROOM_NAME) REFERENCES ROOM(ROOM_NAME)
);

CREATE TABLE USER_ROOMS
(
USER_EMAIL VARCHAR(40),
ROOM_NAME VARCHAR(40),
USER_TYPE INT,
PRIMARY KEY(USER_EMAIL, ROOM_NAME),
CONSTRAINT FK_USERMEMBER FOREIGN KEY(USER_EMAIL) REFERENCES USER(USER_EMAIL),
CONSTRAINT FK_ROOMMEMBER FOREIGN KEY(ROOM_NAME) REFERENCES ROOM(ROOM_NAME)
);

DESC USER;
DESC PLATFORM;
DESC ROOM;
DESC REQUESTS;
DESC USER_ROOMS;

SELECT * FROM USER;