INSERT INTO PLATFORM VALUES('NETFLIX', 'MOBILE', 1, 149);
INSERT INTO PLATFORM VALUES('NETFLIX', 'BASIC', 1, 199);
INSERT INTO PLATFORM VALUES('NETFLIX', 'STANDARD', 2, 499);
INSERT INTO PLATFORM VALUES('NETFLIX', 'PREMIUM', 4, 649);
INSERT INTO PLATFORM VALUES('HOTSTAR', 'SUPER', 2, 75);
INSERT INTO PLATFORM VALUES('HOTSTAR', 'PREMIUM', 4, 299);
INSERT INTO PLATFORM VALUES('AMAZON_PRIME', 'PRIME', 3, 179);
INSERT INTO PLATFORM VALUES('ZEE5', 'PREMIUM', 3, 50);
INSERT INTO PLATFORM VALUES('SONYLIV', 'PREMIUM', 2, 85);
INSERT INTO PLATFORM VALUES('SONYLIV', 'WWE', 2, 25);
INSERT INTO PLATFORM VALUES('AHA', 'TELUGU', 3, 35);

SELECT * FROM USER;
SELECT * FROM PLATFORM;
SELECT * FROM ROOM;
SELECT * FROM USER_ROOMS;
SELECT * FROM REQUESTS;
SELECT DISTINCT PLATFORM_NAME FROM PLATFORM;
SELECT ROOM_NAME, ADMIN_EMAIL, PLATFORM_NAME, PLAN_TYPE FROM ROOM;
