INSERT INTO PLATFORM VALUES('NETFLIX', 'MOBILE', 1, 149);
INSERT INTO PLATFORM VALUES('NETFLIX', 'BASIC', 1, 199);
INSERT INTO PLATFORM VALUES('NETFLIX', 'STANDARD', 2, 499);
INSERT INTO PLATFORM VALUES('NETFLIX', 'PREMIUM', 4, 649);
INSERT INTO PLATFORM VALUES('HOTSTAR', 'SUPER', 2, 75);
INSERT INTO PLATFORM VALUES('HOTSTAR', 'PREMIUM', 4, 299);
INSERT INTO PLATFORM VALUES('AMAZON_PRIME', 'PRIME', 3, 179);
INSERT INTO PLATFORM VALUES('ZEE5', 'PREMIUM', 3, 50);
INSERT INTO PLATFORM VALUES('SONYLIV', 'PREMIUM', 2, 85);
INSERT INTO PLATFORM VALUES('SONYLIV', 'WWE', 2, 25);
INSERT INTO PLATFORM VALUES('AHA', 'TELUGU', 3, 35);

SELECT * FROM USER;
SELECT * FROM PLATFORM;
SELECT * FROM ROOM;
SELECT * FROM USER_ROOMS;
SELECT * FROM REQUESTS;

SELECT DISTINCT ROOM.ROOM_NAME, ADMIN_EMAIL, PLATFORM_NAME, PLAN_TYPE, 
  STREAM_ACCOUNT, STREAM_PASSWORD FROM ROOM, USER_ROOMS WHERE USER_EMAIL = 'admin' 
  AND ADMIN_EMAIL != 'admin';

SELECT DISTINCT PLATFORM_NAME FROM PLATFORM;
SELECT ROOM_NAME, ADMIN_EMAIL, PLATFORM_NAME, PLAN_TYPE FROM ROOM;
SELECT PLAN_PRICE FROM ROOM, PLATFORM WHERE ROOM_NAME = 'a' 
  AND ROOM.PLATFORM_NAME = PLATFORM.PLATFORM_NAME AND ROOM.PLAN_TYPE = PLATFORM.PLAN_TYPE;
SELECT *
  FROM USER, USER_ROOMS WHERE ROOM_NAME = 'qweqweq' 
  AND USER_ROOMS.USER_EMAIL = USER.USER_EMAIL;
  

SELECT DISTINCT ROOM.ROOM_NAME, ADMIN_EMAIL, PLATFORM_NAME, PLAN_TYPE, STREAM_ACCOUNT, STREAM_PASSWORD 
FROM ROOM, USER_ROOMS WHERE ROOM.ROOM_NAME = USER_ROOMS.ROOM_NAME AND USER_EMAIL = 'admin' AND ADMIN_EMAIL != 'admin';

SELECT * FROM REQUESTS;
SELECT * FROM USER_ROOMS;
SELECT * FROM ROOM;

DELETE FROM ROOM WHERE ROOM_NAME = 'qweqweq';
DELETE FROM REQUESTS WHERE USER_EMAIL = 'admin';
INSERT INTO USER_ROOMS VALUES('A', 'aa', 0);
UPDATE ROOM SET MEMBER_CNT = MEMBER_CNT + 1 WHERE ROOM_NAME = 'aa';

DELETE FROM USER_ROOMS WHERE ROOM_NAME = 'qweqweq'AND USER_EMAIL = 'admin';
UPDATE ROOM SET MEMBER_CNT = MEMBER_CNT - 1 WHERE ROOM_NAME = 'qweqweq';

SELECT ROOM.ROOM_NAME, ROOM.ADMIN_EMAIL, ROOM.PLATFORM_NAME, ROOM.PLAN_TYPE 
  FROM ROOM, USER_ROOMS
  WHERE ROOM.ROOM_NAME = USER_ROOMS.ROOM_NAME AND
  USER_ROOMS.USER_EMAIL != 'A' AND 
  MEMBER_CNT < CAPACITY;
  
SELECT COUNT(*) FROM USER_ROOMS WHERE USER_TYPE = 1 AND ROOM_NAME = "C1";
SELECT * FROM ROOM;
SELECT * FROM USER_ROOMS;
SELECT ROOM.ROOM_NAME, ROOM.ADMIN_EMAIL, ROOM.PLATFORM_NAME, ROOM.PLAN_TYPE FROM ROOM, USER_ROOMS WHERE USER_EMAIL NOT IN 
(SELECT USER_EMAIL FROM USER_ROOMS WHERE ROOM.ROOM_NAME = USER_ROOMS.ROOM_NAME)
ORDER BY ROOM_NAME;
SELECT ROOM.ROOM_NAME, ROOM.ADMIN_EMAIL, ROOM.PLATFORM_NAME, ROOM.PLAN_TYPE FROM ROOM, USER_ROOMS; WHERE
  USER_ROOMS.USER_EMAIL = 'A' AND
  ROOM.ROOM_NAME != USER_ROOMS.ROOM_NAME AND
  MEMBER_CNT < CAPACITY



